### ISSUE TITLE
SSR workers don't spawn when `channels` app is added

### ISSUE THREAD

**Issue by pranaypratyush** [malj/django-parcel-ssr#2]
Isn't the entry point for the ssr system the template backend `setup` method?
If so then why doesn't it run after `channels` takes over?

**Comment by malj** [comment]
The entry point is the custom `ssr.setup()` method invoked in `wsgi.py`, to avoid bootstrapping the system when invoking non `runserver` management commands. Do you know of a better entry point for initializing the workers without interfering with other `manage.py` commands?

I suspect that the method doesn't get called in your case because `channels` replaces the WSGI app with the ASGI one. Try moving the initialization code to your `ASGI_APPLICATION` module, as specified in `settings.py` (probably `routing.py`):

```
import ssr
ssr.setup()
```

**Comment by pranaypratyush** [comment]
Thanks. That worked.

**Comment by pranaypratyush** [comment]
But now I seem to be having trouble serving static files. `GET /static/dist/template.css` returns 404. 
A quick inspection tells me it wasn't being generated in the WSGI app either, but it was being served nonetheless.

**Comment by malj** [comment]
Static files shouldn't be WSGI/ASGI related in any way. Did you add the path to the static dir to your `STATICFILES_DIRS` in `settings.py`, as per installation instructions? 

```python
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, '.ssr', 'static'),
)
```
